name: smart
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+81

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any

  bloc: ^8.1.2
  meta: any
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  uuid: any
  geolocator: ^11.0.0

  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.4.0

  appwrite: ^12.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  flutter_spinkit: ^5.2.0
  loading_animations: ^2.2.0

  url_launcher: ^6.2.5
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.3
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
  transparent_image: ^2.0.1

  shimmer: ^3.0.0
  flutter_rating_stars: ^1.0.3+4
  pinput: ^3.0.1
  google_maps_flutter: ^2.6.0
  dio: ^5.3.0
  flutter_dotenv: ^5.1.0

  flutter_localization: ^0.1.13
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: 2.2.19

flutter_native_splash:
  color: "#ED5434"
  image: "Assets/splash.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/app_icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  fonts:
    - family: AppIcons
      fonts:
        - asset: Assets/fonts/AppIcons.ttf

  generate: true

  uses-material-design: true
  assets:
    - Assets/
    - Assets/icons/
    - Assets/fonts/
    - .env
